ignite/accounts/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [  path('create/', views.create_view, name='create'),
                 path('profile/', views.profile, name="profile"),
                 path('update/', views.update_view, name="update"),
                 path('changepassword/', views.change_password_view, name="chpass"),
                 path('delete/<username>/', views.delete_view),
                 path('send_friend/', views.find_friends_view, name='search'),
                 path('accept_friend/<requestID>/', views.accept_friend_view, name='accept_friend_request'),
                 path('requests/', views.see_friend_requests_view, name="requests"),
                 path('login/', views.login_view, name ='login'),
                 path('logout/', views.logout_view, name ='logout'),
            ]
            

ignite/activities/urls.py
from django.urls import path
from . import views

urlpatterns = [path('create/', views.create_activity),
               path('get/', views.get_all_activities),
               path('view/<id>/', views.get_by_id),
               path('<id>/delete/', views.delete_activity),
               path('<id>/update/', views.update_activity),
               path('<socialScore>/<physicalScore>/<moneyScore>/<weather>/<counter>/', views.chooseActivities, name='choose_activity'),
               path('<lon>/<lat>/', views.start_activity, name='explorer'), 
               path('map/', views.explore, name='map') 
]

ignite/ignite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('activities/', include(('activities.urls', 'activities'), namespace="activities")),
    path('mood_quizzes/', include(('mood_quizzes.urls', 'mood_quizzes'), namespace="mood_quizzes")),
    path('accounts/', include(('accounts.urls','accounts'), namespace="accounts")),
    path('start_page/', include(('start_page.urls', 'start_page'), namespace="start_page")),
    path('', views.main)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ignite/mood_quizzes/urls.py
from django.urls import path
from . import views

urlpatterns = [ path('createQuestion/', views.create_view),
                path('readQuestions/', views.list_view),
                path('readQuestions/<qtype>/', views.questions_by_type),
                path('readQuestion/<id>/', views.question_by_id),
                path('deleteQuestion/<id>/', views.delete_question_by_id),
                path('deleteQuestions/<qtype>/', views.delete_questions_by_type),
                path('deleteAllQuestions/', views.delete_all_questions),
                path('updateQuestionType/<id>/', views.update_type),
                path('updateQuestionText/<id>/', views.update_text),
                path('updateQuestion/<id>/', views.update_question),
                path('quiz/', views.get_quiz, name='quiz')
]

ignite/start_page/urls.py
from django.urls import path
from . import views

urlpatterns = [path('get/', views.get_data, name='get_start_page')]

ignite/start_page/models.py
from django.db import models

# Create your models here.

ignite/start_page/views.py
from django.shortcuts import render
from datetime import datetime
import requests
from accounts.views import get_streaks
from django.contrib.gis.geoip2 import GeoIP2


def get_time(request):
    """
    method that gets the server time at request
    """
    current_datetime = datetime.now()  
    time = current_datetime.strftime("%I:%M %p")
    return time


def get_temperature(request):
    """
    method that gets weather details from the ip using an API
    """
    key = "9fa76c16db4ea6572cdc950e6ec3ed42"
    city = ""

    g = GeoIP2() # to compute location from ip/city

    # ip = request.META.get('REMOTE_ADDR', None)
    ip = '86.121.188.6' # because server runs on local host
    if ip:
        city = g.city(ip)['city']
    else:
        city = 'Bucharest' 

    url1 = f"http://api.openweathermap.org/geo/1.0/direct?q={city}&limit=5&appid={key}"

    r1 = requests.get(url1).json() # get data from api
    lon = r1[0]["lon"]
    lat = r1[0]["lat"]

    url2 = f"https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={key}"
    r2 = requests.get(url2).json()
    city_weather = {
        'city': city,
        'temperature': [r2['main']['temp'], int(r2['main']['temp'] - 273.15), int(1.8 * (r2['main']['temp'] - 273) + 32)],
        'description': r2['weather'][0]['description'],
        'icon': f"https://openweathermap.org/img/wn/{r2['weather'][0]['icon']}@2x.png"
    }

    return city_weather


def get_data(request):
    """
    method that computes the data needed to render start page
    """
    if request.user.is_anonymous: # User isn't logged in
        return render(request, "global/index.html")

    time = get_time(request)
    city_weather = get_temperature(request)
    streaks = get_streaks(request)
    return render(request, "global/start_page.html", {"time" : time, "weather" : city_weather, "streaks": streaks})

ignite/templates/global/explorer.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="w-100 h-100">

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <style type="text/css">
        #map {
            position: relative;
            height: 90% !important;
            width: 100%;
            z-index: -50;
        }
    </style>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Ignite</title>
</head>

<body style="background-color: #FFEEC4">
    <a href="{% url 'start_page:get_start_page' %}"><img
            style="height: 60px; top:10px; margin-left:45%; margin-bottom:10px; position:relative"
            src="{% static 'global_images/logo.png' %}" /> </a>
    <div style="height: 100%; width:100%; position:absolute" id="map"></div>
    <a style="position:absolute; top:90%; margin-left:-50%; box-sizing:content-box"
        href="{% url 'start_page:get_start_page' %}" class="btn btn-lg btn-secondary mb-3">Go to home page</a>
    <script
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDyariNg9tgX0GBtdB2I_syXBuiN3BOBNs&callback=initMap&libraries=&v=weekly"
        async>
        </script>

    <script>
        function initMap() {
            const coords = {
                lat: parseFloat("{{lat}}"),
                lng: parseFloat("{{lon}}")
            };

            const map = new google.maps.Map(
                document.getElementById("map"), {

                zoom: 17.56,
                center: coords,
            });

            var first_name = "{{user.first_name}}"
            var last_name = "{{user.last_name}}"
            new google.maps.Marker({
                position: map.getCenter(),
                map: map,
                label: first_name[0] + last_name[0]
            });

            const friends = JSON.parse("{{friends|escapejs}}");

            for (const [key, value] of Object.entries(friends)) {
                console.log(value)
                var f_name = value[1]
                var l_name = value[0]
                new google.maps.Marker({
                    position: { lat: parseFloat(value[2]), lng: parseFloat(value[3]) },
                    map: map,
                    label: f_name[0] + l_name[0]
                });
            }
        }
    </script>



</body>

ignite/templates/global/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="w-100 h-100">

<head>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

  <title>Ignite</title>
</head>

<body class="w-100 h-100"
  style="background-image:url('../../static/global_images/background.png'); background-size: cover;">
  <div class="w-100 h-100 d-flex flex-column justify-content-center align-items-center">
    <img style="height: 128px" class="mb-4" src="{% static 'global_images/logo.png' %}" />
    <a href="{% url 'accounts:login' %}" class="btn btn-lg btn-secondary mb-3">Login</a>
    <a href="{% url 'accounts:create' %}" class="btn btn-lg btn-secondary">Register</a>
  </div>
</body>

</html>

ignite/templates/global/start_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="w-100 h-100">

<head>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;1,400&display=swap"
    rel="stylesheet">
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

  <title>Ignite</title>
</head>

<body class="w-100 h-100"
  style="background-image:url('../../static/global_images/background.png'); background-size: cover;">
  <div class="d-flex flex-column justify-content-center align-items-center">
    <div style="height:100px">

    </div>
    <div class="d-flex flex-column justify-content-center align-items-center">
      <img style="height: 20vh;" src="{% static 'global_images/logo.png' %}" />
    </div>
    <div class="d-flex flex-column justify-content-center align-items-center">
      <h1 style="font-family: 'Roboto', sans-serif;" class="display-4">{{ time }}</h1>
    </div>
    <div class="d-flex flex-column justify-content-center align-items-center">
      {% if streaks == 0 %}
      <p style="font-size:1.6em; font-weight:500; font-family: 'Roboto', sans-serif;"> Take the quiz to get an activity!
      </p>
      {% else %}
      <p style="color: #fc4961;font-size:1.6em; font-weight:900; font-family: 'Roboto', sans-serif;"> {{streaks}}
        activities! You're on fire!</p>
      {% endif %}
      <img src="{{ weather.icon }}">
      <p style="font-size:1.2em; font-weight:500; font-family: 'Roboto', sans-serif;"> {{ weather.temperature.0 }} K /
        {{weather.temperature.1 }} C / {{ weather.temperature.2 }} F</p>
      <p></p>
    </div>
    <div style="min-width: 150px;">
      <a href="{% url 'mood_quizzes:quiz' %}" class="btn btn-lg btn-block btn-secondary mb-3">Quiz</a>
    </div>
    <div style="min-width: 150px;">
      <a href="{% url 'activities:map' %}" class="btn btn-lg btn-block btn-secondary mb-3">Explore</a>
    </div>
    <div style="min-width: 150px;">
      <a href="{% url 'accounts:profile' %}" class="btn btn-lg btn-block btn-secondary mb-3">Profile</a>
    </div>
    <div style="min-width: 150px;">
      <a href="{% url 'accounts:logout' %}" class="btn btn-lg btn-block btn-secondary mb-3">Logout</a>
    </div>

  </div>

</body>

</html>

ignite/templates/global/your_activity.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="w-100 h-100">

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <style type="text/css">
        #map {
            height: 400px;
            width: 400px;
        }

        h1,
        h2,
        h3,
        h4,
        h5,
        p,
        em {
            font-family: 'Roboto', sans-serif !important;
        }

        h2 {
            color: #308d46;
        }

        h2,
        h4,
        h5 {
            font-weight: normal !important;
        }

        #container {
            position: relative;
            width: 60%;
            box-sizing: border-box;
            margin: auto;
            align-items: center;
            justify-content: center;
            margin-top: 20px;
        }

        #fcell {
            height: 400px;
            width: 400px;
            border-style: solid;
            border-color: #F09078;
            background-color: #F09078;
            padding: 10px 10px 10px 10px;
        }

        #buttons {
            position: relative;
            box-sizing: border-box;
            margin: auto;
            align-items: center;
            justify-content: center;
        }

        #buttons>* {
            margin-right: 30px;
            margin-left: 30px;
        }

        #desc {
            margin-left: 10px;
            margin-top: 15px;
        }

        #txt {
            margin-left: 25px;
        }

        #loc {
            margin-left: 100px;
            margin-top: 10%;
        }
    </style>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Ignite</title>
</head>

<body style="background-color: #FFEEC4">

    <a href="{% url 'start_page:get_start_page' %}"><img style="height: 60px; margin: 20px auto auto 25px"
            src="{% static 'global_images/logo.png' %}" /> </a>
    <div class="main">
        <h1 class="text-center">Ignite your world!</h1>
        <h2 class="text-center" id="q">Have you tried <em>{{ activity.name }}</em>
        </h2>
        <div class="d-flex" id="container">
            <div id="fcell">
                <h3 id="desc">Activity description:</h3>
                <h4 id="txt">{{ activity.description }}</h4>
                <h3 id="loc">Suggested location:</h3>
            </div>
            <div id="map" class="d-flex flex-sm-row"></div>
            <script
                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDyariNg9tgX0GBtdB2I_syXBuiN3BOBNs&callback=initMap&libraries=&v=weekly"
                async>
                </script>

            <script>
                function initMap() {
                    const coords = {
                        lat: parseFloat("{{activity.lat}}"),
                        lng: parseFloat("{{activity.lon}}")
                    };

                    const map = new google.maps.Map(
                        document.getElementById("map"), {

                        zoom: 17.56,
                        center: coords,
                    });

                    new google.maps.Marker({
                        position: map.getCenter(),
                        map: map
                    });
                }
            </script>
        </div>
    </div>
    <br />
    <div id="buttons" class="d-flex">
        <a href="{% url 'start_page:get_start_page' %}" class="btn btn-lg btn-secondary mb-3">Go to home page</a>
        <a href="{% url 'activities:choose_activity' socialScore=socialscore physicalScore=physicalscore moneyScore=moneyscore weather=weather counter=counter %}"
            class="btn btn-lg btn-secondary mb-3">Change activity</a>
        <a href="{% url 'activities:explorer' lon=activity.lon lat=activity.lat %}"
            class="btn btn-lg btn-secondary mb-3">Start activity!</a>
    </div>
</body>