ignite/accounts/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [  path('create/', views.create_view, name='create'),
                 path('profile/', views.profile, name="profile"),
                 path('update/', views.update_view, name="update"),
                 path('changepassword/', views.change_password_view, name="chpass"),
                 path('delete/<username>/', views.delete_view),
                 path('send_friend/', views.find_friends_view, name='search'),
                 path('accept_friend/<requestID>/', views.accept_friend_view, name='accept_friend_request'),
                 path('requests/', views.see_friend_requests_view, name="requests"),
                 path('login/', views.login_view, name ='login'),
                 path('logout/', views.logout_view, name ='logout'),
            ]
            

ignite/ignite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('activities/', include(('activities.urls', 'activities'), namespace="activities")),
    path('mood_quizzes/', include(('mood_quizzes.urls', 'mood_quizzes'), namespace="mood_quizzes")),
    path('accounts/', include(('accounts.urls','accounts'), namespace="accounts")),
    path('start_page/', include(('start_page.urls', 'start_page'), namespace="start_page")),
    path('', views.main)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ignite/start_page/urls.py
from django.urls import path
from . import views

urlpatterns = [path('get/', views.get_data, name='get_start_page')]

ignite/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    friends = models.ManyToManyField("User", blank=True)
    profile_picture = models.ImageField(upload_to='uploads/')
    lon = models.DecimalField(max_digits=20, decimal_places=10, default=0.0)
    lat = models.DecimalField(max_digits=20, decimal_places=10, default=0.0)
    streaks = models.IntegerField(default=0)


class Friend_Request(models.Model):
    from_user = models.ForeignKey(User, related_name='from_user', 
    on_delete = models.CASCADE)

    to_user = models.ForeignKey(User, related_name='to_user',
    on_delete=models.CASCADE)

    def __str__(self):
        return u'{0}'.format(self.from_user.username)
    

ignite/accounts/forms.py
from multiprocessing import AuthenticationError
from django import forms
from django.shortcuts import get_object_or_404
from .models import Friend_Request, User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class UserCreateForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = User
        fields = ['username', 'first_name', 'last_name',
                   'email', 'profile_picture',
                   'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Sign Up!', css_class='btn-secondary'))


class ChangePasswordForm(forms.Form):
    old_password=forms.PasswordInput()
    new_password=forms.PasswordInput()
    reenter_password=forms.PasswordInput()


class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100,
                               required=False,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=False,
                             widget=forms.TextInput(attrs={'class': 'form-control'}))

    profile_picture = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ['username', 'email', 'profile_picture']


class AddFriendForm(forms.Form):
    username = forms.CharField(max_length=100, label="Username",help_text="Enter your friends username" )


class FriendRequestsForm(forms.Form):
    def __init__(self, user, *args, **kwargs):
        super(FriendRequestsForm, self).__init__(*args, **kwargs)
        current_user = get_object_or_404(User, username=user)
        self.fields['requests'] = forms.ModelChoiceField(queryset= Friend_Request.objects.filter(to_user=current_user), to_field_name="id")

    class Meta:    
        fields = ('requests', )


class LoginForm(forms.Form):
    username = forms.CharField(
        label='',
        widget=forms.TextInput(
            attrs = {
                'placeholder': 'username or email',
            }
        )
    )

    password = forms.CharField(
        label='', 
        widget=forms.PasswordInput(
            attrs = {
                'placeholder': 'password'
            }
        )
    )

ignite/accounts/views.py
from multiprocessing import context
import re
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from .forms import FriendRequestsForm, AddFriendForm, UserCreateForm, LoginForm, UpdateUserForm, ChangePasswordForm
from .models import Friend_Request, User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import logout, authenticate, login, update_session_auth_hash
import requests
from django.contrib.gis.geoip2 import GeoIP2


def get_client_ip(request):
    """
    method that retrievs the ip adress of the user that makes the request
        args: request
        returns: ip address    
    """
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def update_location(request, user):
    """
        method that update the current location of the user that makes the request
        Args: request, user
        Returns: 0 
    """ 

    key = "9fa76c16db4ea6572cdc950e6ec3ed42"
    current_user = get_object_or_404(User, username = user.username)
    ip = '86.121.188.6' # get_client_ip(request)
    # because server runs on local host, can't extract the location from ip
    
    g = GeoIP2()
    if ip:
        city = g.city(ip)['city']
    else:
        city = 'Bucharest' 

    url1 = f"http://api.openweathermap.org/geo/1.0/direct?q={city}&limit=5&appid={key}" # connection to api

    r1 = requests.get(url1).json()
    lon = r1[0]["lon"]
    lat = r1[0]["lat"]

    current_user.lon = lon
    current_user.lat = lat
    current_user.save()

    return 0


def increment_streaks(request):
    """
    method that increments the streaks of a user
        Args: request
        Returns: 0
    """

    current_user = get_object_or_404(User, username = request.user.username)
    current_user.streaks += 1
    current_user.save()
    return 0


@login_required
def get_streaks(request):
    """
    method that returns the streak number of the session/request user
    """
    return get_object_or_404(User, username = request.user.username).streaks


def getListFriends(request):
    """
    method that returns a list of the request user's friends
    """
    return request.user.friends.all()


#Views
def login_view(request):
    """
    method for the user login
        Args: request
        Returns: renders login page 
    """
    if not request.user.is_anonymous: # Somebody already connected tries to access
        return HttpResponseRedirect('/start_page/get/')

    context = {}
    form = LoginForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            user = authenticate(username=form.cleaned_data.get('username'), password=form.cleaned_data.get('password'))
            if user is not None:
                update_location(request, user)
                login(request=request, user=user)
                return HttpResponseRedirect('/start_page/get/')
    
    context['form'] = form
    return render(request, "accounts/login.html", context)


def create_view(request):
    """
    method for user creation
        Args: request
        Returns: renders the user creation form
    """
    
    if not request.user.is_anonymous: # Somebody already connected tries to access
        return HttpResponseRedirect('/start_page/get/')
    context = {}
    form = UserCreateForm(request.POST or None, request.FILES or None)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/accounts/login")

    if form.is_valid():
        form.save()
    
    context['form'] = form
    return render(request, "accounts/create.html", context)


def detailView(request, username):
    context = {}
    context["data"] = User.objects.get(username = username)

    return render(request, 'accounts/profile.html', context)


@login_required
def update_view(request):
    """
    method that updates the details of a user
        Args: requesst
        Returns: the update page
    """

    context = {}

    object = get_object_or_404(User, username = request.user.username)

    form = UpdateUserForm(request.POST or None, instance = object)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect("../profile/")
    
    context["form"] = form
    return render(request, "accounts/update.html", context)


@login_required
def change_password_view(request):
    """
    request for changing the user's password
        Args: request
        Returns: the HTML changepassword page
    """

    context = {}

    form = PasswordChangeForm(user=request.user, data=request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return profile(request)

        else:
            context['error'] = "Passwords don't match."
    
    context["form"] = form
    return render(request, "accounts/changepassword.html", context)


def delete_view(request, username):
    """
    method that deletes a user from the database
        Args: request, username
        Returns: the HTML page for deleting the user
    """

    context = {}
    object = get_object_or_404(User, username = username)

    if request.method == "POST":
        object.delete()
        return HttpResponseRedirect("/")
    
    return render(request, "accounts/deleteView.html", context)


@login_required
def profile(request):
    """
    method that returns the profile of a user and the list of friends
        Args: request
        Returns: the profile page
    """
    context = {}

    user = request.user
    context["data"] = user
    context["friends"] = user.friends.all()

    return render(request, 'accounts/profile.html', context)


@login_required
def find_friends_view(request):
    """
    method that finds the user for the friend request
        Args: request
        Returns: 1 HTML page with the appropiate response 
    """
    form = AddFriendForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            username = form.cleaned_data.get('username')
            try:
                to_user = User.objects.get(username=username)
                if request.user == to_user:
                    return render(request, "accounts/findFriends.html", {"form": form, "error":"I dont think you're so lonely you're adding yourself as a friend..."})
                elif to_user in request.user.friends.all():
                    return render(request, "accounts/findFriends.html", {"form": form, "error":"Already friends"})

                return add_friend_view(request, to_user)
            except:
                return render(request, "accounts/findFriends.html", {"form": form, "error":"No user with that username"})


    return render(request, "accounts/findFriends.html", {"form": form})


@login_required
def add_friend_view(request, to_user):
    """
    method that adds the new friend to the current user's friendlist
        Args: request, to_user (username of the new friend)
        Returns: HTML page with appropiate response
    """
    from_user = request.user

    form = AddFriendForm()

    if form.is_valid():
        form.save()
        return HttpResponseRedirect("../profile/")

    if to_user == None:
        return render(request, "accounts/findFriends.html", {"form": form, "error":"Invalid"})
    
    friend_req, created = Friend_Request.objects.get_or_create(from_user=from_user, 
    to_user = to_user)

    if created:
        return render(request, "accounts/findFriends.html", {"form": form, "error":"Request sent."})
    else:
        return render(request, "accounts/findFriends.html", {"form": form, "error":"A request already exists."})
    

@login_required
def see_friend_requests_view(request):
    """
    method that returns all the pending friend requests
        Args: request
        Returns: HTML page
    """
    form = FriendRequestsForm(user=request.user.username)

    if request.method == "POST":
        id = request.POST['requests']
        return render(request, 'accounts/seeRequests.html', {'form':form, 'error': accept_friend_view(request, id)})

    return render(request, 'accounts/seeRequests.html', {'form':form})


@login_required
def accept_friend_view(request, requestID):
    """
    method that accepts a pending friend request
        Args: request, requestID (id of the friend request)
        Returns: a message according to the user's action (accept/deny)
    """
    friend_req = Friend_Request.objects.get(id=requestID)
    if friend_req.to_user == request.user:
        friend_req.to_user.friends.add(friend_req.from_user)
        friend_req.from_user.friends.add(friend_req.to_user)
        friend_req.delete()
        return "Request accepted"
    else:
        return "Request denied"


@login_required
def logout_view(request):
    """
    method that logs out the current logged in user
        Args: request
        Returns: redirects to the login/register page
    """
    logout(request)
    # Redirect to a success page.
    return HttpResponseRedirect("../../")

ignite/templates/accounts/changepassword.html
{% load crispy_forms_tags %}
{% load static %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>


<body style="background-image:url('../../static/global_images/background.png'); background-size: cover;">
    <a href="{% url 'start_page:get_start_page' %}"><img style="height: 7%; margin: 15px auto auto 20px"
            src="{% static 'global_images/logo.png' %}" /></a>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-8">
                <br>
                <h1 class="mt-2 text-center">Update password</h1>
                <br>
                {% if error %}
                <p>{{ error }}</p>
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    {{form|crispy}}


                    <input type="submit" class="btn btn-secondary" value="Update!">
                    <input type="hidden" name="next" value="{{ next }}">
                </form>



            </div>
        </div>
    </div>
</body>

ignite/templates/accounts/create.html
{% load crispy_forms_tags %}
{% load static %}


<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body style="background-image:url('../../static/global_images/background.png'); background-size: cover;">
    <img style="height: 7%; margin: 15px auto auto 20px" src="{% static 'global_images/logo.png' %}" />
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-8">
                {% block content %}
                <br>
                <h1 class="mt-2 text-center">Registration</h1>
                <br>
                {%crispy form %}

                {% endblock %}

            </div>
        </div>
    </div>
</body>

</html>

ignite/templates/accounts/deleteView.html
<div class="main">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}
        Are you want to delete this item ?
        <input type="submit" value="Yes" />
        <a href="/">Cancel </a>
    </form>
</div

ignite/templates/accounts/findFriends.html
{% load crispy_forms_tags %}
{% load static %}




<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body style="background-image:url('../../static/global_images/background.png'); background-size: cover;">
    <a href="{% url 'start_page:get_start_page' %}"><img style="height: 7%; margin: 15px auto auto 20px"
            src="{% static 'global_images/logo.png' %}" /></a>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-8">
                <br>
                <h1 class="mt-2 text-center">Add friend</h1>
                <br>
                {% if error %}
                <p>{{ error }}</p>
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    {{form|crispy}}


                    <input type="submit" class="btn btn-secondary" value="Add friend!">
                    <input type="hidden" name="next" value="{{ next }}">
                </form>

            </div>
        </div>
    </div>
</body>

</html>

ignite/templates/accounts/login.html
{% load crispy_forms_tags %}
{% load static %}




<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body style="background-image:url('../../static/global_images/background.png'); background-size: cover;">
    <a><img style="height: 7%; margin: 15px auto auto 20px" src="{% static 'global_images/logo.png' %}" /></a>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-8">
                <br>
                <h1 class="mt-2 text-center">Login</h1>
                <br>
                {% block content %}

                {% if form.errors %}
                <p>Your username and password didn't match. Please try again.</p>
                {% endif %}

                {% if next %}
                {% if user.is_authenticated %}
                <p>Your account doesn't have access to this page. To proceed,
                    please login with an account that has access.</p>
                {% else %}
                <p>Please login to see this page.</p>
                {% endif %}
                {% endif %}
                <form method="post" action="{% url 'accounts:login' %}">
                    {% csrf_token %}
                    {{form|crispy}}


                    <input type="submit" class="btn btn-secondary" value="Log back in!">
                    <input type="hidden" name="next" value="{{ next }}">
                </form>

                {% endblock %}


            </div>
        </div>
    </div>
</body>

</html>

ignite/templates/accounts/profile.html
{% load crispy_forms_tags %}
{% load static %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>


<body style="background-image:url('../../static/global_images/background.png'); background-size: cover;">
    <a href="{% url 'start_page:get_start_page' %}"><img style="height: 7%; margin: 15px auto auto 20px"
            src="{% static 'global_images/logo.png' %}" />
    </a>
    <div class="container">
        <div class="container">
            <div class="row d-flex justify-content-center align-items-center">
                <div class="col col-lg-6 mb-4 mb-lg-0">
                    <div class="card mb-3" style="border-radius: .5rem;">
                        <div class="row">
                            <div class="col-md-4 text-center d-flex flex-column justify-content-around"
                                style="border-top-left-radius: .5rem; border-bottom-left-radius: .5rem;">
                                <img src="{{data.profile_picture.url}}" alt="Profile picture" class="img-fluid"
                                    style="width: 180px; border-radius: 10px; margin-left: 1rem; margin-top: 1rem;" />
                                <h5 style="margin-left: 1.2rem;">{{data.first_name}} {{data.last_name}}</h5>
                            </div>
                            <div class="col-md-8">
                                <div class="card-body p-4">
                                    <h6>Profil</h6>
                                    <hr class="mt-0 mb-2">
                                    <h6>Username</h6>
                                    <p class="text-muted">{{data.username}}</p>

                                    <h6>Email</h6>
                                    <p class="text-muted"> {{data.email}}</p>

                                    <h6>Friends</h6>
                                    <hr class="mt-0 mb-2">
                                    <div class="row pt-1">
                                        <div class="col">
                                            {% if not friends %}
                                            <a href="{% url 'accounts:search' %}">
                                                <p class="text-muted">No friends yet. Add them now.</p>
                                            </a>
                                            {% else %}
                                            {% for friend in friends %}
                                            <p class="text-muted"> {{friend.username }}</p>
                                            {% endfor %}
                                            {% endif %}
                                        </div>
                                    </div>
                                    <hr class="mt-0 mb-2">
                                    <div class="row pt-1">
                                        <div class="col">
                                            <a href="{% url 'accounts:update' %}" class="btn btn-sm btn-secondary mb-3">
                                                Update profile </a>
                                            <a href="{% url 'accounts:chpass' %}" class="btn btn-sm btn-secondary mb-3">
                                                Change password </a>
                                            <a href="{% url 'accounts:search' %}" class="btn btn-sm btn-secondary mb-3">
                                                Add friends </a>
                                            <a href="{% url 'accounts:requests' %}"
                                                class="btn btn-sm btn-secondary mb-3"> Accept requests </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

ignite/templates/accounts/seeRequests.html
{% load crispy_forms_tags %}
{% load static %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>


<body style="background-image:url('../../static/global_images/background.png'); background-size: cover;">
    <a href="{% url 'start_page:get_start_page' %}"><img style="height: 7%; margin: 15px auto auto 20px"
            src="{% static 'global_images/logo.png' %}" /> </a>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-8">
                <br>
                <h1 class="mt-2 text-center">Friend requests</h1>
                <br>
                {% if error %}
                <p>{{ error }}</p>
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    {{form|crispy}}


                    <input type="submit" class="btn btn-secondary" value="Accept request">
                    <input type="hidden" name="next" value="{{ next }}">
                </form>



            </div>
        </div>
    </div>
</body>

ignite/templates/accounts/update.html
{% load crispy_forms_tags %}
{% load static %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>


<body style="background-image:url('../../static/global_images/background.png'); background-size: cover;">
    <a href="{% url 'start_page:get_start_page' %}"><img style="height: 7%; margin: 15px auto auto 20px"
            src="{% static 'global_images/logo.png' %}" /> </a>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-8">
                <br>
                <h1 class="mt-2 text-center">Update profile</h1>
                <br>

                <form method="post">
                    {% csrf_token %}
                    {{form|crispy}}


                    <input type="submit" class="btn btn-secondary" value="Update!">
                    <input type="hidden" name="next" value="{{ next }}">
                </form>



            </div>
        </div>
    </div>
</body>